language: node_js
node_js:
- "11.10.1" #due to a bug in 11.11 related to jest, we need to downgrade until a fix is available in node
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    branch: source
before_script:
- "yarn global add gatsby-cli"
- "yarn"
script:
- "yarn run test"
after_success:
- "yarn run deploy"